FROM python:3.11-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get dist-upgrade -y && \
    apt-get install -y \
    curl \
    build-essential && \
    apt-get autoremove -y && \
    apt-get clean

COPY requirements.txt ./

RUN pip install -r requirements.txt

##docker build -t pls-api-base -f Dockerfile.base .
