data:
  raw_path: data/raw
  processed_path: data/processed
  outputs_path: data/outputs
  evaluation_path: data/evaluation
  path: data/processed/dataset.csv
  text_col: texto_original
  label_col: label
  test_size: 0.2
  val_size: 0.1
  random_state: 42
model:
  classifier_type: random_forest
  random_state: 42
  test_size: 0.2
  validation_size: 0.1
training:
  max_iter: 1000
  learning_rate: 0.01
  batch_size: 32
pls:
  max_length: 150
  min_length: 50
  num_beams: 4
  temperature: 0.8
evaluation:
  metrics:
  - rouge
  - bleu
  - meteor
  save_predictions: true
  generate_report: true
